CREATE TABLE "login" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "email" VARCHAR(255) UNIQUE NOT NULL,
  "password" VARCHAR(255) NOT NULL,
  "user_type" VARCHAR(50) NOT NULL
);

CREATE TABLE "agencies" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "login_id" INTEGER UNIQUE,
  "name" TEXT NOT NULL
);

CREATE TABLE "brokers" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "agency_id" INTEGER NOT NULL,
  "login_id" INTEGER UNIQUE,
  "name" TEXT NOT NULL,
  "email" TEXT NOT NULL,
  "phone" TEXT NOT NULL,
  "creci" TEXT NOT NULL
);

CREATE TABLE "brokerProperty" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "broker_id" INTEGER,
  "property_id" INTEGER
);

CREATE TABLE "availability" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "broker_id" INTEGER NOT NULL,
  "starts_at" TIMESTAMP(0) NOT NULL,
  "ends_at" TIMESTAMP(0) NOT NULL,
  "description" TEXT
);

CREATE TABLE "properties" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "agency_id" INTEGER NOT NULL,
  "address" TEXT NOT NULL,
  "price" INTEGER NOT NULL,
  "status" TEXT NOT NULL
);

CREATE TABLE "events" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "event_type" TEXT NOT NULL,
  "property_id" INTEGER NOT NULL,
  "starts_at" TIMESTAMP(0) NOT NULL,
  "ends_at" TIMESTAMP(0) NOT NULL,
  "description" TEXT
);

CREATE TABLE "clients" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" TEXT NOT NULL,
  "email" TEXT NOT NULL,
  "phone" TEXT NOT NULL
);

CREATE TABLE "visits" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "client_id" INTEGER NOT NULL,
  "broker_id" INTEGER NOT NULL,
  "property_id" INTEGER NOT NULL,
  "starts_at" TIMESTAMP(0) NOT NULL,
  "ends_at" TIMESTAMP(0) NOT NULL,
  "status" TEXT NOT NULL
);

COMMENT ON COLUMN "events"."event_type" IS '"Available","maintenance"';

COMMENT ON COLUMN "visits"."status" IS '"confirmed", "canceled"';

ALTER TABLE "brokers" ADD CONSTRAINT "brokers_agency_id_foreign" FOREIGN KEY ("agency_id") REFERENCES "agencies" ("id");

ALTER TABLE "events" ADD CONSTRAINT "events_property_id_foreign" FOREIGN KEY ("property_id") REFERENCES "properties" ("id");

ALTER TABLE "visits" ADD CONSTRAINT "visits_property_id_foreign" FOREIGN KEY ("property_id") REFERENCES "properties" ("id");

ALTER TABLE "visits" ADD CONSTRAINT "visits_broker_id_foreign" FOREIGN KEY ("broker_id") REFERENCES "brokers" ("id");

ALTER TABLE "properties" ADD CONSTRAINT "properties_agency_id_foreign" FOREIGN KEY ("agency_id") REFERENCES "agencies" ("id");

ALTER TABLE "visits" ADD CONSTRAINT "visits_client_id_foreign" FOREIGN KEY ("client_id") REFERENCES "clients" ("id");

ALTER TABLE "availability" ADD CONSTRAINT "availability_broker_id_foreign" FOREIGN KEY ("broker_id") REFERENCES "brokers" ("id");

ALTER TABLE "agencies" ADD CONSTRAINT "agencies_login_id_foreign" FOREIGN KEY ("login_id") REFERENCES "login" ("id");

ALTER TABLE "brokers" ADD CONSTRAINT "brokers_login_id_foreign" FOREIGN KEY ("login_id") REFERENCES "login" ("id");

ALTER TABLE "brokers" ADD CONSTRAINT "brokerProperty_broker_id_foreign" FOREIGN KEY ("id") REFERENCES "brokerProperty" ("broker_id");

ALTER TABLE "properties" ADD CONSTRAINT "brokerProperty_property_id_foreign" FOREIGN KEY ("id") REFERENCES "brokerProperty" ("property_id");
